server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/bookswork_identity"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "b3dud2Vha3Blcm1pbmRwb3NzaWJseXJ1bm5pbmdmYXJ0aGVycHJldmVudHZvd2VsYmU="
